export default [{
    id:'jv41',
    username : 'jv4',
    title : 'Test Blog 1',
    date : Date.now(),
    content: 'The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.The new Tesla Cybertruck was unveiled last week and people have already placed a ton of orders. Tesla CEO Elon Musk updated on Twitter that the company has already received 200K orders so far.',
    likes: '1',
    share:'localhost:3000/jv41',
    background:"black"
}];